(defproject accumulation "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.10.3"]
                 [de.ubercode.clostache/clostache "1.4.0"]
                 [clojure-tensorflow "0.2.4"]
                 [org.clojure/test.check "1.1.0"]
                 [prismatic/schema "1.1.12"]
                 [ring/ring-core "1.9.2"]
                 [ring/ring-codec "1.1.3"]
                 [clj-time "0.15.2"]
                 [compojure "1.6.2"]
                 [clj-http "3.12.1"]
                 [robert/bruce "0.8.0"]
                 [org.clojure/core.async "1.3.610"]
                 [cheshire "5.10.0"]
                 [com.cemerick/url "0.1.1"]
                 [danlentz/clj-uuid "0.1.9"]
                 [org.clojure/core.match "1.0.0"]
                 [commons-codec/commons-codec "1.15"]
                 [com.taoensso/carmine "3.1.0"]
                 [clojure-csv/clojure-csv "2.0.2"]
                 [me.raynes/fs "1.4.6"]
                 [cc.qbits/hayt "4.1.0"]
                 [com.velisco/clj-ftp "0.3.15"]
                 [com.rpl/specter "1.1.3"]
                 [org.clojure/math.combinatorics "0.1.6"]
                 [org.clojure/data.xml "0.1.0-beta3"]
                 [clj-ssh "0.5.14"]
                 [thinktopic/cortex "0.9.22"]
                 [org.clojure/data.zip "1.0.0"]
                 [aysylu/loom "1.0.2"]
                 [com.walmartlabs/lacinia "0.38.0"]])
